import { Condition } from "./const"

export const weatherDict: {[id: number]: Condition[]} = {
200: [Condition.Thunderstorm, Condition.Rain],
201: [Condition.Thunderstorm, Condition.Rain],
202: [Condition.Thunderstorm, Condition.Rain],
210: [Condition.Thunderstorm],
211: [Condition.Thunderstorm],
212: [Condition.Thunderstorm],
221: [Condition.Thunderstorm],
230: [Condition.Thunderstorm, Condition.Drizzle],
231: [Condition.Thunderstorm, Condition.Drizzle],
232: [Condition.Thunderstorm, Condition.Drizzle],

300: [Condition.Drizzle],
301: [Condition.Drizzle],
302: [Condition.Drizzle],
310: [Condition.Rain, Condition.Drizzle],
311: [Condition.Rain, Condition.Drizzle],
312: [Condition.Rain, Condition.Drizzle],
313: [Condition.Rain, Condition.Drizzle],
314: [Condition.Rain, Condition.Drizzle],
321: [Condition.Rain, Condition.Drizzle],

500: [Condition.Rain],
501: [Condition.Rain],
502: [Condition.Rain],
503: [Condition.Rain],
504: [Condition.Rain],
511: [Condition.Rain],
520: [Condition.Rain],
521: [Condition.Rain],
522: [Condition.Rain],
531: [Condition.Rain],

600: [Condition.Snow],
601: [Condition.Snow],
602: [Condition.Snow],
611: [Condition.Snow],
612: [Condition.Snow, Condition.Rain],
613: [Condition.Snow, Condition.Rain],
615: [Condition.Snow, Condition.Rain],
616: [Condition.Snow, Condition.Rain],
620: [Condition.Snow],
621: [Condition.Snow],
622: [Condition.Snow],

701: [Condition.Atmosphere],
711: [Condition.Atmosphere],
721: [Condition.Atmosphere],
731: [Condition.Atmosphere],
741: [Condition.Atmosphere],
751: [Condition.Atmosphere],
761: [Condition.Atmosphere],
762: [Condition.Atmosphere],
771: [Condition.Atmosphere, Condition.Tornado],
781: [Condition.Atmosphere, Condition.Tornado],
800: [Condition.Clear],
801: [Condition.Clear, Condition.Clouds],
802: [Condition.Clear, Condition.Clouds],
803: [Condition.Clouds],
804: [Condition.Clouds],
}
